apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8scompliant
spec:
  crd:
    spec:
      names:
        kind: K8sCompliant
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          properties:
            message:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      code:
        - engine: K8sNativeValidation
          source:
             validations:
             - expression: "object.metadata.name != null"
               messageExpression: "missing required name, requires: object.metadata.name"